In [13]:
from pathlib import Path
import pandas as pd
import numpy as np

In [14]:
# Récupérer le répertoire de travail actuel
PROJECT_DIR = Path.cwd()

# Si Jupyter est lancé depuis prediction/, remonter à la racine
if not (PROJECT_DIR / "data" / "dataset.csv").exists():
    PROJECT_DIR = PROJECT_DIR.parent

# Chemins des datasets
DATASET_PATH = PROJECT_DIR / "data" / "dataset.csv"
OUTPUT_PATH = PROJECT_DIR / "data" / "dataset_ml.csv"

print("Dataset :", DATASET_PATH)
print("Fichier présent :", DATASET_PATH.exists())

Dataset : c:\Users\david\Documents\David\Etudes\Projet\M2\OpenData\car_accident_od\data\dataset.csv
Fichier présent : True

In [15]:
df = pd.read_csv(DATASET_PATH, low_memory=False)

print("Dimensions :", df.shape)
display(df.head())

Dimensions : (657865, 57)

,Num_Acc,id_usager,id_vehicule,num_veh_x,place,catu,grav,sexe,an_nais,trajet,...,num_veh_y,senc,catv,obs,obsm,choc,manv,motor,occutc,year
0,202300000001,203 851 184,155 680 557,A01,1,Conducteur,Blessé léger,Homme,1978.0,Loisirs,...,A01,PK ou PR ou numéro d'adresse postale croissant,Scooter < 50 cm3,Sans objet,Aucun,Arrière droit,Sans changement de direction,Hydrocarbures,NaN,2023
1,202300000001,203 851 184,155 680 557,A01,1,Conducteur,Blessé léger,Homme,1978.0,Loisirs,...,A01,PK ou PR ou numéro d'adresse postale croissant,Scooter < 50 cm3,Sans objet,Aucun,Arrière droit,Sans changement de direction,Hydrocarbures,NaN,2023
2,202300000002,203 851 182,155 680 556,A01,1,Conducteur,Indemne,Femme,1997.0,Autre,...,A01,PK ou PR ou numéro d'adresse postale décroissant,Voiture,Sans objet,Piéton,Avant,Sans changement de direction,Hydrocarbures,NaN,2023
3,202300000002,203 851 183,155 680 556,A01,10,Piéton,Blessé hospitalisé,Homme,1997.0,Autre,...,A01,PK ou PR ou numéro d'adresse postale décroissant,Voiture,Sans objet,Piéton,Avant,Sans changement de direction,Hydrocarbures,NaN,2023
4,202300000003,203 851 180,155 680 554,B01,1,Conducteur,Blessé hospitalisé,Homme,1987.0,Non renseigné,...,B01,PK ou PR ou numéro d'adresse postale croissant,Cyclomoteur <50cm3,Sans objet,Véhicule,Avant,Tourne à droite,Hydrocarbures,NaN,2023

In [16]:
df = pd.read_csv(DATASET_PATH, low_memory=False)

print("Dimensions :", df.shape)
display(df.head())

Dimensions : (657865, 57)

,Num_Acc,id_usager,id_vehicule,num_veh_x,place,catu,grav,sexe,an_nais,trajet,...,num_veh_y,senc,catv,obs,obsm,choc,manv,motor,occutc,year
0,202300000001,203 851 184,155 680 557,A01,1,Conducteur,Blessé léger,Homme,1978.0,Loisirs,...,A01,PK ou PR ou numéro d'adresse postale croissant,Scooter < 50 cm3,Sans objet,Aucun,Arrière droit,Sans changement de direction,Hydrocarbures,NaN,2023
1,202300000001,203 851 184,155 680 557,A01,1,Conducteur,Blessé léger,Homme,1978.0,Loisirs,...,A01,PK ou PR ou numéro d'adresse postale croissant,Scooter < 50 cm3,Sans objet,Aucun,Arrière droit,Sans changement de direction,Hydrocarbures,NaN,2023
2,202300000002,203 851 182,155 680 556,A01,1,Conducteur,Indemne,Femme,1997.0,Autre,...,A01,PK ou PR ou numéro d'adresse postale décroissant,Voiture,Sans objet,Piéton,Avant,Sans changement de direction,Hydrocarbures,NaN,2023
3,202300000002,203 851 183,155 680 556,A01,10,Piéton,Blessé hospitalisé,Homme,1997.0,Autre,...,A01,PK ou PR ou numéro d'adresse postale décroissant,Voiture,Sans objet,Piéton,Avant,Sans changement de direction,Hydrocarbures,NaN,2023
4,202300000003,203 851 180,155 680 554,B01,1,Conducteur,Blessé hospitalisé,Homme,1987.0,Non renseigné,...,B01,PK ou PR ou numéro d'adresse postale croissant,Cyclomoteur <50cm3,Sans objet,Véhicule,Avant,Tourne à droite,Hydrocarbures,NaN,2023

In [17]:
selected_cols = [
    "sexe", "catu", "catv", "atm", "lum",
    "col", "choc", "manv", "plan", "surf",
    "nbv", "secu1", "infra", "age", "place"
]

target_col = "grav"

required_cols = [
    col for col in selected_cols if col != "age"
] + ["grav", "an", "an_nais", "Num_Acc"]

missing_cols = [
    col for col in required_cols
    if col not in df.columns
]

print("Colonnes manquantes :", missing_cols)

if missing_cols:
    raise ValueError(f"Colonnes absentes : {missing_cols}")
else:
    print("Toutes les colonnes nécessaires sont présentes.")

Colonnes manquantes : []
Toutes les colonnes nécessaires sont présentes.

In [18]:
missing_stats = df[required_cols].isna().sum().to_frame("Valeurs manquantes")

missing_stats["Pourcentage (%)"] = (
    missing_stats["Valeurs manquantes"] / len(df) * 100
).round(2)

display(
    missing_stats.sort_values(
        "Pourcentage (%)",
        ascending=False
    )
)

         Valeurs manquantes  Pourcentage (%)
an_nais                9453             1.44
sexe                      0             0.00
catu                      0             0.00
catv                      0             0.00
lum                       0             0.00
atm                       0             0.00
choc                      0             0.00
manv                      0             0.00
plan                      0             0.00
col                       0             0.00
surf                      0             0.00
nbv                       0             0.00
infra                     0             0.00
secu1                     0             0.00
place                     0             0.00
grav                      0             0.00
an                        0             0.00
Num_Acc                   0             0.00

In [19]:
df = pd.read_csv(DATASET_PATH, low_memory=False)

print("Dimensions :", df.shape)
display(df.head())

Dimensions : (657865, 57)

,Num_Acc,id_usager,id_vehicule,num_veh_x,place,catu,grav,sexe,an_nais,trajet,...,num_veh_y,senc,catv,obs,obsm,choc,manv,motor,occutc,year
0,202300000001,203 851 184,155 680 557,A01,1,Conducteur,Blessé léger,Homme,1978.0,Loisirs,...,A01,PK ou PR ou numéro d'adresse postale croissant,Scooter < 50 cm3,Sans objet,Aucun,Arrière droit,Sans changement de direction,Hydrocarbures,NaN,2023
1,202300000001,203 851 184,155 680 557,A01,1,Conducteur,Blessé léger,Homme,1978.0,Loisirs,...,A01,PK ou PR ou numéro d'adresse postale croissant,Scooter < 50 cm3,Sans objet,Aucun,Arrière droit,Sans changement de direction,Hydrocarbures,NaN,2023
2,202300000002,203 851 182,155 680 556,A01,1,Conducteur,Indemne,Femme,1997.0,Autre,...,A01,PK ou PR ou numéro d'adresse postale décroissant,Voiture,Sans objet,Piéton,Avant,Sans changement de direction,Hydrocarbures,NaN,2023
3,202300000002,203 851 183,155 680 556,A01,10,Piéton,Blessé hospitalisé,Homme,1997.0,Autre,...,A01,PK ou PR ou numéro d'adresse postale décroissant,Voiture,Sans objet,Piéton,Avant,Sans changement de direction,Hydrocarbures,NaN,2023
4,202300000003,203 851 180,155 680 554,B01,1,Conducteur,Blessé hospitalisé,Homme,1987.0,Non renseigné,...,B01,PK ou PR ou numéro d'adresse postale croissant,Cyclomoteur <50cm3,Sans objet,Véhicule,Avant,Tourne à droite,Hydrocarbures,NaN,2023

In [20]:
selected_cols = [
    "sexe", "catu", "catv", "atm", "lum",
    "col", "choc", "manv", "plan", "surf",
    "nbv", "secu1", "infra", "age", "place"
]

target_col = "grav"

required_cols = [
    col for col in selected_cols if col != "age"
] + ["grav", "an", "an_nais", "Num_Acc"]

missing_cols = [
    col for col in required_cols
    if col not in df.columns
]

print("Colonnes manquantes :", missing_cols)

if missing_cols:
    raise ValueError(f"Colonnes absentes : {missing_cols}")
else:
    print("Toutes les colonnes nécessaires sont présentes.")

Colonnes manquantes : []
Toutes les colonnes nécessaires sont présentes.

In [21]:
missing_stats = df[required_cols].isna().sum().to_frame("Valeurs manquantes")

missing_stats["Pourcentage (%)"] = (
    missing_stats["Valeurs manquantes"] / len(df) * 100
).round(2)

display(
    missing_stats.sort_values(
        "Pourcentage (%)",
        ascending=False
    )
)

         Valeurs manquantes  Pourcentage (%)
an_nais                9453             1.44
sexe                      0             0.00
catu                      0             0.00
catv                      0             0.00
lum                       0             0.00
atm                       0             0.00
choc                      0             0.00
manv                      0             0.00
plan                      0             0.00
col                       0             0.00
surf                      0             0.00
nbv                       0             0.00
infra                     0             0.00
secu1                     0             0.00
place                     0             0.00
grav                      0             0.00
an                        0             0.00
Num_Acc                   0             0.00

In [22]:
# Créer un dataset indépendant
df_ml = df[required_cols].copy()

# Convertir les années en valeurs numériques
df_ml["an"] = pd.to_numeric(df_ml["an"], errors="coerce")
df_ml["an_nais"] = pd.to_numeric(
    df_ml["an_nais"],
    errors="coerce"
)

# Calculer l'âge au moment de l'accident
df_ml["age"] = df_ml["an"] - df_ml["an_nais"]

# Identifier les âges incohérents
invalid_age = (
    df_ml["age"].notna()
    & ~df_ml["age"].between(0, 110)
)

print("Âges incohérents :", invalid_age.sum())

# Remplacer les âges incohérents par NaN
df_ml.loc[invalid_age, "age"] = np.nan

# Vérifier les résultats
print("Dimensions :", df_ml.shape)
print("Âges manquants :", df_ml["age"].isna().sum())

display(
    df_ml[["an", "an_nais", "age"]].head(10)
)

Âges incohérents : 191
Dimensions : (657865, 19)
Âges manquants : 9644

     an  an_nais   age
0  2023   1978.0  45.0
1  2023   1978.0  45.0
2  2023   1997.0  26.0
3  2023   1997.0  26.0
4  2023   1987.0  36.0
5  2023   1987.0  36.0
6  2023   1984.0  39.0
7  2023   1984.0  39.0
8  2023   2001.0  22.0
9  2023   1995.0  28.0

In [23]:
categorical_cols = [
    "sexe", "catu", "catv", "atm", "lum",
    "col", "choc", "manv", "plan", "surf",
    "secu1", "infra", "place"
]

for col in categorical_cols:
    print(f"\n{'=' * 40}")
    print(f"{col.upper()} : {df_ml[col].nunique()} catégories")
    print(df_ml[col].value_counts(dropna=False).to_string())

========================================
SEXE : 3 catégories
sexe
Homme    443015
Femme    205767
-1         9083

========================================
CATU : 3 catégories
catu
Conducteur    489762
Passager      117384
Piéton         50719

========================================
CATV : 32 catégories
catv
Voiture                     413150
Véhicule utilitaire          45227
Moto > 125 cm3               44330
Bicyclette                   30118
Cyclomoteur <50cm3           21566
Scooter < 50 cm3             17939
Scooter <= 125 cm3           13171
Moto <= 125 cm3              10054
EDP motorisé                  9907
Autobus                       6438
Scooter > 125 cm3             6436
PL + remorque                 5063
Poids lourd > 7,5t            4405
Voiturette                    4089
Tracteur + semi-remorque      3506
43                            3407
VAE                           3231
Autre                         2981
Autocar                       2500
Poids lourd <= 7,5t           2402
0                             1494
Tracteur agricole             1430
36                            1182
EDP non motorisé              1175
Tramway                        991
Engin spécial                  758
39                             294
Tracteur routier seul          201
35                             165
42                             141
41                              96
-1                              18

========================================
ATM : 10 catégories
atm
Normale                523515
Pluie légère            71518
Temps couvert           24888
Pluie forte             14867
Temps éblouissant       12071
Brouillard / fumée       4033
Autre                    2860
Neige / grêle            2251
Vent fort / tempête      1821
Non renseigné              41

========================================
LUM : 6 catégories
lum
Plein jour                        441843
Nuit avec éclairage allumé        103590
Nuit sans éclairage public         64189
Crépuscule ou aube                 42145
Nuit avec éclairage non allumé      6085
-1                                    13

========================================
COL : 8 catégories
col
Par le côté (2 véhicules)              215889
Autre collision                        157456
Par l’arrière (2 véhicules)             91102
Frontale (2 véhicules)                  73646
En chaîne (≥3 véhicules)                41714
Sans collision                          39529
Collisions multiples (≥3 véhicules)     34630
Non renseigné                            3899

========================================
CHOC : 11 catégories
choc
Avant                         239826
Avant gauche                   98686
Avant droit                    85990
Arrière                        63007
Côté gauche                    43251
Côté droit                     37905
Aucun                          37671
Arrière gauche                 22378
Arrière droit                  18472
Chocs multiples / tonneaux     10339
Non renseigné                    340

========================================
MANV : 28 catégories
manv
Sans changement de direction     279903
Même sens, même file              69992
Tourne à gauche                   54763
Inconnue                          37894
Déport à gauche                   27260
Autre                             21771
Dépassement gauche                20758
Insertion                         18988
Tourne à droite                   18700
Traverse chaussée                 16542
Arrêté                            16169
Déport à droite                   13837
Évitement                         10342
À contresens                       7174
Changement file à gauche           6700
Entre 2 files                      5939
Changement file à droite           5909
Stationnement                      4150
En marche arrière                  4135
Demi-tour                          4088
Dépassement droite                 3188
Stationné avec occupants           2450
Ouverture de porte                 2009
Sur trottoir                       1933
Couloir bus, même sens             1652
Franchissement du terre-plein      1111
Couloir bus, sens inverse           283
Non renseigné                       225

========================================
PLAN : 5 catégories
plan
Partie rectiligne    541423
Courbe à gauche       55390
Courbe à droite       52832
En S                   7760
Non renseigné           460

========================================
SURF : 10 catégories
surf
Normale               530092
Mouillée              118778
Autre                   2788
Verglacée               2121
Enneigée                1086
Flaques                  955
Corps gras / huile       789
Non renseigné            620
Boue                     354
Inondée                  282

========================================
SECU1 : 11 catégories
secu1
Ceinture                    385762
Casque                      120976
Non déterminable             80210
Aucun équipement             56284
Non renseigné                 8660
Dispositif enfants            4050
Autre                          677
Gants (2RM/3RM)                570
Gilet réfléchissant            410
Airbag (2RM/3RM)               250
Gants + Airbag (2RM/3RM)        16

========================================
INFRA : 11 catégories
infra
Aucun                   548177
Carrefour aménagé        39510
Autre                    22386
Pont                     11458
Bretelle d’échangeur      8520
Tunnel                    8094
Non renseigné             6517
Zone piétonne             5658
Chantier                  4981
Voie ferrée               2073
Zone de péage              491

========================================
PLACE : 11 catégories
place
 1     488930
 2      73918
 10     50720
 3      12587
 4      11494
 9       6676
 7       6153
 5       3617
 8       2847
 6        896
-1         27

In [24]:
numeric_cols = ["age", "nbv"]

for col in numeric_cols:
    values = pd.to_numeric(df_ml[col], errors="coerce")

    print(f"\n{col.upper()}")
    print(values.describe())
    print("Valeurs non numériques :", df_ml[col].notna().sum() - values.notna().sum())

AGE
count    648221.000000
mean         38.508677
std          18.908997
min           0.000000
25%          23.000000
50%          35.000000
75%          52.000000
max         110.000000
Name: age, dtype: float64
Valeurs non numériques : 0

NBV
count    657734.000000
mean          2.362131
std           1.424488
min          -1.000000
25%           2.000000
50%           2.000000
75%           3.000000
max          12.000000
Name: nbv, dtype: float64
Valeurs non numériques : 131

In [25]:
# Vérifier les valeurs particulières
for col in ["sexe", "nbv", "place", "plan", "secu1"]:
    print(f"\n{'=' * 45}")
    print(f"COLONNE : {col.upper()}")
    print(f"{'=' * 45}")

    print(
        df_ml[col]
        .value_counts(dropna=False)
        .to_string()
    )

=============================================
COLONNE : SEXE
=============================================
sexe
Homme    443015
Femme    205767
-1         9083

=============================================
COLONNE : NBV
=============================================
nbv
2               391197
4                77980
1                65039
3                54240
6                18006
0                16142
5                11003
 -1              10590
8                 5538
-1                3598
7                 1856
10                1260
9                  796
12                 279
11                 210
#VALEURMULTI       129
#ERREUR              2

=============================================
COLONNE : PLACE
=============================================
place
 1     488930
 2      73918
 10     50720
 3      12587
 4      11494
 9       6676
 7       6153
 5       3617
 8       2847
 6        896
-1         27

=============================================
COLONNE : PLAN
=============================================
plan
Partie rectiligne    541423
Courbe à gauche       55390
Courbe à droite       52832
En S                   7760
Non renseigné           460

=============================================
COLONNE : SECU1
=============================================
secu1
Ceinture                    385762
Casque                      120976
Non déterminable             80210
Aucun équipement             56284
Non renseigné                 8660
Dispositif enfants            4050
Autre                          677
Gants (2RM/3RM)                570
Gilet réfléchissant            410
Airbag (2RM/3RM)               250
Gants + Airbag (2RM/3RM)        16

In [26]:
nbv_numeric = pd.to_numeric(df_ml["nbv"], errors="coerce")

invalid_nbv = df_ml[
    df_ml["nbv"].notna() & nbv_numeric.isna()
]

print("Nombre de valeurs non numériques :", len(invalid_nbv))

print("\nValeurs concernées :")
display(invalid_nbv["nbv"].value_counts(dropna=False))

Nombre de valeurs non numériques : 131

Valeurs concernées :

nbv
#VALEURMULTI    129
#ERREUR           2
Name: count, dtype: int64

In [27]:
# Nettoyer le nombre de voies
df_ml["nbv"] = pd.to_numeric(
    df_ml["nbv"].astype("string").str.strip(),
    errors="coerce"
)

# -1 signifie une information inconnue
df_ml.loc[df_ml["nbv"] == -1, "nbv"] = np.nan

# Vérifier les résultats
print("Valeurs manquantes nbv :", df_ml["nbv"].isna().sum())
print("Valeurs manquantes age :", df_ml["age"].isna().sum())

display(df_ml[["nbv", "age"]].describe())

Valeurs manquantes nbv : 14319
Valeurs manquantes age : 9644

            nbv            age
count  643546.0  648221.000000
mean   2.436255      38.508677
std    1.348775      18.908997
min         0.0       0.000000
25%         2.0      23.000000
50%         2.0      35.000000
75%         3.0      52.000000
max        12.0     110.000000

In [28]:
categorical_cols = [
    "sexe", "catu", "catv", "atm", "lum",
    "col", "choc", "manv", "plan", "surf",
    "secu1", "infra", "place"
]

for col in categorical_cols:
    df_ml[col] = df_ml[col].astype("string").str.strip()

    df_ml[col] = df_ml[col].replace({
        "-1": "Non renseigné",
        "#ERREUR": "Non renseigné",
        "#VALEURMULTI": "Non renseigné"
    })

print("Nettoyage des catégories terminé.")

print("\nValeurs de sexe :")
print(df_ml["sexe"].value_counts(dropna=False))

print("\nValeurs de place :")
print(df_ml["place"].value_counts(dropna=False))

Nettoyage des catégories terminé.

Valeurs de sexe :
sexe
Homme            443015
Femme            205767
Non renseigné      9083
Name: count, dtype: Int64

Valeurs de place :
place
1                488930
2                 73918
10                50720
3                 12587
4                 11494
9                  6676
7                  6153
5                  3617
8                  2847
6                   896
Non renseigné        27
Name: count, dtype: Int64

In [29]:
# Variables utilisées par le formulaire
features = [
    "sexe", "catu", "catv", "atm", "lum",
    "col", "choc", "manv", "plan", "surf",
    "nbv", "secu1", "infra", "age", "place"
]

# Variable cible
target = "grav"

# Identifiant conservé pour séparer les accidents
group_col = "Num_Acc"

# Dataset final pour le Machine Learning
df_ml_final = df_ml[
    [group_col] + features + [target]
].copy()

# Contrôles
assert len(df_ml_final) == len(df_ml)
assert df_ml_final.columns.is_unique
assert df_ml_final["grav"].notna().all()

print("Dimensions :", df_ml_final.shape)
print("Accidents uniques :", df_ml_final["Num_Acc"].nunique())

print("\nRépartition des catégories de gravité :")
print(df_ml_final["grav"].value_counts(dropna=False))

display(df_ml_final.head())

# Export
df_ml_final.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8"
)

print("\nDataset ML enregistré :", OUTPUT_PATH)

Dimensions : (657865, 17)
Accidents uniques : 273226

Répartition des catégories de gravité :
grav
Indemne               278216
Blessé léger          262421
Blessé hospitalisé     99843
Tué                    16928
-1                       457
Name: count, dtype: int64

,Num_Acc,sexe,catu,catv,atm,lum,col,choc,manv,plan,surf,nbv,secu1,infra,age,place,grav
0,202300000001,Homme,Conducteur,Scooter < 50 cm3,Pluie légère,Plein jour,Sans collision,Arrière droit,Sans changement de direction,Partie rectiligne,Mouillée,2,Casque,Aucun,45.0,1,Blessé léger
1,202300000001,Homme,Conducteur,Scooter < 50 cm3,Pluie légère,Plein jour,Sans collision,Arrière droit,Sans changement de direction,Partie rectiligne,Mouillée,1,Casque,Aucun,45.0,1,Blessé léger
2,202300000002,Femme,Conducteur,Voiture,Pluie forte,Nuit avec éclairage allumé,Autre collision,Avant,Sans changement de direction,Partie rectiligne,Mouillée,3,Ceinture,Aucun,26.0,1,Indemne
3,202300000002,Homme,Piéton,Voiture,Pluie forte,Nuit avec éclairage allumé,Autre collision,Avant,Sans changement de direction,Partie rectiligne,Mouillée,3,Aucun équipement,Aucun,26.0,10,Blessé hospitalisé
4,202300000003,Homme,Conducteur,Cyclomoteur <50cm3,Pluie légère,Plein jour,Frontale (2 véhicules),Avant,Tourne à droite,Partie rectiligne,Mouillée,4,Casque,Carrefour aménagé,36.0,1,Blessé hospitalisé

Dataset ML enregistré : c:\Users\david\Documents\David\Etudes\Projet\M2\OpenData\car_accident_od\data\dataset_ml.csv

In [30]:
valid_gravities = [
    "Indemne",
    "Blessé léger",
    "Blessé hospitalisé",
    "Tué"
]

# Conserver uniquement les gravités connues
df_ml_final = df_ml_final[
    df_ml_final["grav"].isin(valid_gravities)
].copy()

print("Dimensions après nettoyage :", df_ml_final.shape)
print("Accidents uniques :", df_ml_final["Num_Acc"].nunique())

print("\nRépartition finale des gravités :")
print(df_ml_final["grav"].value_counts())

# Réexporter le dataset nettoyé
df_ml_final.to_csv(
    OUTPUT_PATH,
    index=False,
    encoding="utf-8"
)

print("\nDataset ML mis à jour :", OUTPUT_PATH)

Dimensions après nettoyage : (657408, 17)
Accidents uniques : 273226

Répartition finale des gravités :
grav
Indemne               278216
Blessé léger          262421
Blessé hospitalisé     99843
Tué                    16928
Name: count, dtype: int64

Dataset ML mis à jour : c:\Users\david\Documents\David\Etudes\Projet\M2\OpenData\car_accident_od\data\dataset_ml.csv